#!/usr/bin/env bash
# Create databases, roles and grants.
#
# The SQL is generated by python3 rather than assembled in bash: passwords can
# contain quotes and dollar signs, and shell interpolation would either mangle
# them or leak them into the process list. The generated file is mode 0600,
# owned by postgres, and removed on exit.
set -euo pipefail
# shellcheck source=/dev/null
source "${DP_LIB:?dp.sh not found}"
# shellcheck source=/dev/null
source "${DP_PACK_ROOT:?}/pg-lib.sh"

dp_require_root
PORT="$(dp_param port 5432)"

DATABASES="$(dp_param databases)"
USERS="$(dp_param users)"

if [ -z "$DATABASES" ] || [ "$DATABASES" = "[]" ]; then
  if [ -z "$USERS" ] || [ "$USERS" = "[]" ]; then
    dp_skip "no databases or users requested"
  fi
fi

SQL_FILE="$(mktemp /tmp/dpagent-pg-XXXXXX.sql)"
trap 'rm -f "$SQL_FILE"' EXIT
chmod 0600 "$SQL_FILE"

DP_DATABASES="$DATABASES" DP_USERS="$USERS" python3 - "$SQL_FILE" <<'PY'
import json, os, sys

def ident(name: str) -> str:
    """Quote an SQL identifier."""
    if not name or not isinstance(name, str):
        raise SystemExit(f"invalid identifier: {name!r}")
    return '"' + name.replace('"', '""') + '"'

def literal(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"

def load(raw):
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        raise SystemExit(f"param is not valid JSON: {raw[:80]}")
    return data if isinstance(data, list) else [data]

databases = load(os.environ.get("DP_DATABASES", ""))
users = load(os.environ.get("DP_USERS", ""))

out = ["-- generated by dpagent; safe to run repeatedly", "\\set ON_ERROR_STOP on", ""]

for db in databases:
    name = db if isinstance(db, str) else db.get("name")
    out.append(
        f"SELECT 'CREATE DATABASE {ident(name)}'\n"
        f"WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = {literal(name)})\\gexec"
    )
out.append("")

for user in users:
    if isinstance(user, str):
        user = {"name": user}
    name = user.get("name")
    if not name:
        raise SystemExit("every entry in `users` needs a name")
    password = user.get("password")

    if password:
        out.append(
            f"DO $dpagent$ BEGIN\n"
            f"  IF EXISTS (SELECT FROM pg_roles WHERE rolname = {literal(name)}) THEN\n"
            f"    ALTER ROLE {ident(name)} WITH LOGIN PASSWORD {literal(password)};\n"
            f"  ELSE\n"
            f"    CREATE ROLE {ident(name)} WITH LOGIN PASSWORD {literal(password)};\n"
            f"  END IF;\n"
            f"END $dpagent$;"
        )
    else:
        out.append(
            f"DO $dpagent$ BEGIN\n"
            f"  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = {literal(name)}) THEN\n"
            f"    CREATE ROLE {ident(name)} WITH LOGIN;\n"
            f"  END IF;\n"
            f"END $dpagent$;"
        )

    for db in user.get("databases", []):
        out.append(f"GRANT ALL PRIVILEGES ON DATABASE {ident(db)} TO {ident(name)};")
    if user.get("superuser"):
        out.append(f"ALTER ROLE {ident(name)} WITH SUPERUSER;")

# PostgreSQL 15 stopped granting CREATE on the `public` schema to PUBLIC by
# default (a deliberate upstream security change). `GRANT ... ON DATABASE`
# above covers CONNECT/TEMP on the database itself but not the schema inside
# it, so a role that owns no objects yet still can't CREATE TABLE there -
# `airflow db migrate` and a fresh dbt run both hit exactly this. Schema
# grants are per-database, so \connect into each one to apply them.
for user in users:
    if isinstance(user, str):
        continue
    name = user.get("name")
    for db in user.get("databases", []):
        out.append(f"\\connect {ident(db)}")
        out.append(f"GRANT ALL ON SCHEMA public TO {ident(name)};")
if any(user.get("databases") if not isinstance(user, str) else None for user in users):
    out.append("\\connect postgres")

with open(sys.argv[1], "w", encoding="utf-8") as fh:
    fh.write("\n".join(out) + "\n")
PY

dp_run chown postgres:postgres "$SQL_FILE"

if [ "$DP_DRY_RUN" = "1" ]; then
  dp_info "would apply this SQL (passwords shown as literals are masked in the agent log):"
  grep -vE "PASSWORD" "$SQL_FILE" >&2 || true
  dp_info "(password statements withheld from this preview)"
else
  dp_run runuser -u postgres -- psql -v ON_ERROR_STOP=1 -p "$PORT" -d postgres -f "$SQL_FILE"
fi

# Report what exists now, without echoing any secret.
if [ "$DP_DRY_RUN" != "1" ]; then
  existing="$(pg_query "SELECT datname FROM pg_database WHERE datistemplate = false;" | tr '\n' ' ')"
  dp_ok "databases present: ${existing}"
fi
