"""Everything about a pipeline-OWNED dbt project (`dbt_project:` in
pipeline.yaml, docs/hg-dbt-project.md) that must hold *before* it is trusted:
what its content is (for the approval hash), that all of it lives inside the
directory the pipeline is allowed to own, and that each stage's selectors
actually select models.

Pure file inspection + one `dbt ls` helper - no database, no dbt run. The
approval hash (approval.py), the loader's refusals, `validate` step 3 and the
runtime all use the same functions, so "what was approved", "what is allowed"
and "what is run" cannot drift apart: a run executes a private copy made by
`copy_project`, which copies exactly the files the hash covers.

The model for the hash is *everything in the project except generated
output*, not an allow-list of dbt's directory names: dbt executes SQL from
`analyses/`, `snapshots/`, `tests/`, `macros/`, `seeds/` and Python models
too, and a directory type added by a future dbt version would silently fall
outside an allow-list. A stray file that does nothing costs a re-review; a
missing executable one costs the approval its meaning.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path, PurePosixPath

import yaml

# Generated by dbt itself, never authored: excluded from the approval hash
# and from the private copy a run is made from. These are *root-level*
# output directories (plus whatever `target-path`/`packages-install-path`/
# `log-path` redirect them to - see `output_roots`): a directory that merely
# shares the name deeper in the tree (`tests/logs/`) is authored content and
# stays covered. `package-lock.yml` is NOT here - it pins the package
# versions and is exactly what a reviewer approves.
DEFAULT_OUTPUT_ROOTS = frozenset({"target", "dbt_packages", "dbt_modules", "logs"})
_GENERATED_ROOT_FILES = frozenset({".user.yml"})
_GENERATED_ANYWHERE_FILES = frozenset({".DS_Store"})
_GENERATED_ANYWHERE_DIRS = frozenset({"__pycache__"})

# dbt_project.yml keys naming directories dbt reads from or writes to.
_PATH_LIST_KEYS = ("model-paths", "source-paths", "analysis-paths", "test-paths",
                   "seed-paths", "macro-paths", "snapshot-paths", "asset-paths",
                   "docs-paths", "clean-targets")
_PATH_SCALAR_KEYS = ("target-path", "packages-install-path", "log-path")
_SOURCE_DEFAULTS = {"model-paths": ["models"], "analysis-paths": ["analyses"],
                    "test-paths": ["tests"], "seed-paths": ["seeds"],
                    "macro-paths": ["macros"], "snapshot-paths": ["snapshots"]}


class DbtProjectError(Exception):
    pass


def _as_list(value) -> list:
    if value is None:
        return []
    return list(value) if isinstance(value, (list, tuple)) else [value]


def _rel_ok(value: str) -> bool:
    p = PurePosixPath(value)
    return bool(value) and not p.is_absolute() and ".." not in p.parts and not value.startswith("~")


def _config(project: Path) -> dict:
    try:
        cfg = yaml.safe_load((Path(project) / "dbt_project.yml").read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise DbtProjectError(f"dbt_project.yml is not valid YAML: {exc}") from None
    except OSError as exc:
        raise DbtProjectError(f"cannot read dbt_project.yml: {exc}") from None
    if not isinstance(cfg, dict):
        raise DbtProjectError("dbt_project.yml must be a mapping")
    return cfg


def output_roots(project: Path) -> frozenset[str]:
    """Top-level names under `project` that are dbt output, not authored
    content: the defaults plus wherever the project redirected its output."""
    roots = set(DEFAULT_OUTPUT_ROOTS)
    cfg = _config(project)
    for key in _PATH_SCALAR_KEYS:
        value = cfg.get(key)
        if isinstance(value, str) and _rel_ok(value):
            roots.add(PurePosixPath(value).parts[0])
    return frozenset(roots)


def _walk(project: Path, roots: frozenset[str]):
    """(relative PurePosixPath, absolute Path) for every authored entry under
    `project`. Symlinks are listed (never followed) so the caller can refuse
    them."""
    project = Path(project)
    for dirpath, dirnames, filenames in os.walk(project, followlinks=False):
        here = Path(dirpath)
        at_root = here == project
        rel_dir = PurePosixPath(here.relative_to(project).as_posix())
        keep = []
        for d in sorted(dirnames):
            rel = PurePosixPath(d) if at_root else rel_dir / d
            if (at_root and d in roots) or d in _GENERATED_ANYWHERE_DIRS:
                continue
            if (here / d).is_symlink():
                yield rel, here / d            # listed, not descended into
            else:
                keep.append(d)
        dirnames[:] = keep
        for f in sorted(filenames):
            if (at_root and f in _GENERATED_ROOT_FILES) or f in _GENERATED_ANYWHERE_FILES:
                continue
            yield (PurePosixPath(f) if at_root else rel_dir / f), here / f


def project_files(project: Path) -> list[tuple[str, bytes]]:
    """(path relative to `project`, raw bytes) of every authored file, sorted -
    exactly what the approval hash covers. Raises DbtProjectError on a
    symlink: hashing a link's target would hash content that lives outside
    the project and can change without any file in it changing."""
    project = Path(project)
    out = []
    for rel, path in _walk(project, output_roots(project)):
        if path.is_symlink():
            raise DbtProjectError(f"{rel} is a symlink - refused (see check_project)")
        out.append((rel.as_posix(), path.read_bytes()))
    return sorted(out)


def copy_project(project: Path, dest: Path) -> int:
    """Copies exactly the files `project_files` hashes into `dest` and
    nothing else - so what a run executes is, file for file, what the
    approval covered, and generated output (`target/`, a stale
    `dbt_packages/`, `logs/`) never comes along. Returns the file count."""
    Path(dest).mkdir(parents=True, exist_ok=True)
    n = 0
    for rel, _ in project_files(project):
        target = Path(dest) / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(Path(project) / rel, target)
        n += 1
    return n


def _paths_for(project: Path, key: str) -> list[Path]:
    """The directories a dbt_project.yml key names (default if unset), as
    paths under `project` - `seed-paths: [data/seeds]` is a real setting, and
    code that assumed a literal `seeds/` would skip those seeds and let
    models read an empty or missing table."""
    cfg = _config(project)
    values = [v for v in _as_list(cfg.get(key)) if isinstance(v, str) and _rel_ok(v)]
    return [Path(project) / v for v in (values or _SOURCE_DEFAULTS.get(key, []))]


def has_seeds(project: Path) -> bool:
    return any(d.is_dir() and any(d.rglob("*.csv")) for d in _paths_for(project, "seed-paths"))


def count_models(project: Path) -> int:
    return sum(1 for d in _paths_for(project, "model-paths") if d.is_dir() for _ in d.rglob("*.sql"))


def check_project(project: Path) -> None:
    """Refuses a project that reaches outside the directory it is allowed to
    own, or whose content the approval hash cannot see. Raises
    DbtProjectError naming exactly what and where.

    - **Symlinks** anywhere in the project (files or directories): a link's
      content lives elsewhere, is not in the hash, and `shutil.copytree`
      would follow it when the pipeline is published.
    - **Path settings** in dbt_project.yml (`model-paths`, `macro-paths`,
      `seed-paths`, `target-path`, `packages-install-path`, ...) that are
      absolute or contain `..`: dbt would read or write outside the project.
    - **Output redirected onto authored content** (`target-path: macros`):
      the macros would count as generated output and drop out of the hash.
    - **Local packages** (`local:` in packages.yml / dependencies.yml) that
      are absolute or resolve outside the project: their files are not in
      the project, so not in the hash. A local package *inside* the project
      is just more project files and is covered.
    - **Unpinned remote packages**: any non-local package requires a
      `package-lock.yml`, because the hash covers the lock - without one a
      version range resolves to whatever is newest on the day of the run.
    """
    project = Path(project)
    root = project.resolve()
    roots = output_roots(project)
    for rel, path in _walk(project, roots):
        if path.is_symlink():
            raise DbtProjectError(
                f"{rel} is a symlink (-> {os.readlink(path)}) - a dbt project may not "
                f"contain symlinks: the target is outside what the approval hash covers")
        try:
            path.resolve().relative_to(root)
        except ValueError:
            raise DbtProjectError(f"{rel} resolves outside the project") from None

    cfg = _config(project)
    for key in _PATH_LIST_KEYS:
        for value in _as_list(cfg.get(key)):
            if not isinstance(value, str) or not _rel_ok(value):
                raise DbtProjectError(
                    f"dbt_project.yml {key}: {value!r} must be a relative path inside "
                    f"the project (no absolute path, no '..')")
    for key in _PATH_SCALAR_KEYS:
        value = cfg.get(key)
        if value is not None and (not isinstance(value, str) or not _rel_ok(value)):
            raise DbtProjectError(
                f"dbt_project.yml {key}: {value!r} must be a relative path inside the project")
    for key, defaults in _SOURCE_DEFAULTS.items():
        for value in (_as_list(cfg.get(key)) or defaults):
            if isinstance(value, str) and _rel_ok(value) \
                    and PurePosixPath(value).parts[0] in roots:
                raise DbtProjectError(
                    f"dbt_project.yml {key}: {value!r} sits inside a directory the project "
                    f"also uses for generated output ({sorted(roots)}) - authored files there "
                    f"would be excluded from the approval hash")

    has_remote = False
    for fname in ("packages.yml", "dependencies.yml"):
        f = project / fname
        if not f.exists():
            continue
        try:
            doc = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as exc:
            raise DbtProjectError(f"{fname} is not valid YAML: {exc}") from None
        for entry in _as_list(doc.get("packages") if isinstance(doc, dict) else None):
            if not isinstance(entry, dict):
                raise DbtProjectError(f"{fname}: every package must be a mapping, got {entry!r}")
            if "local" in entry:
                local = entry["local"]
                if not isinstance(local, str) or not local:
                    raise DbtProjectError(f"{fname}: a local package path must be a string")
                if PurePosixPath(local).is_absolute():
                    raise DbtProjectError(f"{fname}: local package {local!r} is an absolute path")
                try:
                    (project / local).resolve().relative_to(root)
                except ValueError:
                    raise DbtProjectError(
                        f"{fname}: local package {local!r} resolves outside the project - "
                        f"its files would not be covered by the approval hash") from None
            else:
                has_remote = True
    if has_remote and not (project / "package-lock.yml").exists():
        raise DbtProjectError(
            "packages.yml lists remote packages but there is no package-lock.yml - without "
            "it a version range resolves to whatever is newest on the day of the run, which "
            "no approval can pin. Run `dbt deps` once and commit the lock")


# ------------------------------------------------------------ selectors

def list_selected_models(dbt_bin: str, base_args: list[str], selector: str,
                         *, timeout: int = 120) -> list[str]:
    """Names of the models `selector` selects, via `dbt ls`. `dbt ls` (and
    `dbt run`) exit 0 and select NOTHING for a selector that matches no node
    ("The selection criterion 'x' does not match any enabled nodes", then
    "Nothing to do") - so the exit code says nothing here; the caller must
    treat an empty list as the failure it is. A nonzero exit (a real parse
    error) raises DbtProjectError with dbt's own message."""
    try:
        proc = subprocess.run(
            [dbt_bin, "ls", "--select", selector, "--resource-type", "model",
             "--output", "name", "--quiet", *base_args],
            capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        raise DbtProjectError(f"dbt ls --select {selector!r} timed out after {timeout}s") from None
    if proc.returncode != 0:
        raise DbtProjectError(
            f"dbt ls --select {selector!r} failed:\n{(proc.stderr or proc.stdout).strip()[-2000:]}")
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def check_selectors(dbt_bin: str, base_args: list[str], stages: list) -> list[str]:
    """For every selector of every dbt stage: it must select at least one
    model. Returns the problems (empty = fine). Checked per selector, not per
    stage - a stage `[dim_artist, dim_artsit]` whose typo selects nothing
    would otherwise run the one that matched and report success for a stage
    the manifest claims builds two things."""
    problems = []
    for stage in stages:
        for selector in stage.models:
            try:
                selected = list_selected_models(dbt_bin, base_args, selector)
            except DbtProjectError as exc:
                problems.append(f"stage {stage.name!r}: {exc}")
                continue
            if not selected:
                problems.append(
                    f"stage {stage.name!r}: selector {selector!r} selects 0 models "
                    f"(dbt would exit 0 with 'Nothing to do' and the stage would look "
                    f"successful) - fix the selector or the project")
    return problems
