"""Writes what `plan()` described to disk, and applies procedure migrations
for real.

dpagent has never linked a database driver into its own Python - every
pack's relationship with Postgres goes through `psql` as a subprocess
(`packs/postgres/pg-lib.sh`'s `pg_query`, e.g.), reviewed and auditable the
same way every other command this project runs is. This keeps that shape
rather than adding psycopg2 as a new dependency for one feature.
"""
from __future__ import annotations

import json
import os
import subprocess
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from ..engine.params import resolve_refs
from .generator import dag_tasks
from .loader import Pipeline, Stage


class DeployError(Exception):
    pass


@dataclass
class DeployResult:
    written: list[Path] = field(default_factory=list)
    procedures_applied: list[str] = field(default_factory=list)


def render_dag(pipeline: Pipeline) -> str:
    """A real, importable Airflow DAG - PythonOperator tasks calling into
    `dpagent.pipelines.runtime`, the gate/transform execution engine (not
    built yet). Generated now so the task graph can be reviewed today; it
    becomes runnable the moment runtime.py exists, with no regeneration
    needed - this file only encodes *structure*, never executes anything
    itself.
    """
    tasks = dag_tasks(pipeline)
    lines = [
        f'"""Generated by `dpagent pipeline deploy {pipeline.name}` - do not '
        f'hand-edit.',
        f"",
        f"Source of truth: pipelines/{pipeline.name}/pipeline.yaml. Change that,",
        f"then re-run deploy, instead of editing this file directly - it will",
        f'be overwritten the next time deploy runs."""',
        "from datetime import datetime",
        "",
        "from airflow import DAG",
        "from airflow.operators.python import PythonOperator",
        "",
        "from dpagent.pipelines import runtime",
        "",
        "",
        "with DAG(",
        f'    dag_id="{pipeline.name}",',
        "    schedule_interval=None,",
        "    start_date=datetime(2026, 1, 1),",
        "    catchup=False,",
        '    tags=["dpagent-pipeline"],',
        ") as dag:",
    ]

    for task in tasks:
        if task.kind == "extract":
            call = f'runtime.run_extract(pipeline_name="{pipeline.name}", run_id=run_id)'
        elif task.kind == "gate":
            stage_name = task.id[len("gate_"):]
            call = (f'runtime.run_gate(pipeline_name="{pipeline.name}", '
                    f'stage="{stage_name}", run_id=run_id)')
        else:
            stage_name = task.id[len("transform_"):]
            call = (f'runtime.run_transform(pipeline_name="{pipeline.name}", '
                    f'stage="{stage_name}", run_id=run_id)')
        # `run_id` is dpagent's own runs.id (kind='data'), started by `dpagent
        # pipeline run` before it triggers this DAG - passed through
        # dag_run.conf so every task's stage_runs/gate_runs/events row ties
        # back to that one run, the same run `dpagent audit <run>` reads.
        lines.append(f'    def _{task.id}(dag_run=None, **_):')
        lines.append(f'        run_id = (dag_run.conf or {{}}).get("dpagent_run_id") '
                     f'if dag_run else None')
        lines.append(f'        {call}')
        lines.append(f'')
        lines.append(f'    {task.id} = PythonOperator(')
        lines.append(f'        task_id="{task.id}",')
        lines.append(f'        python_callable=_{task.id},')
        lines.append(f'    )')

    for task in tasks:
        for dep in task.depends_on:
            lines.append(f"    {dep} >> {task.id}")

    return "\n".join(lines) + "\n"


def render_dbt_schema(pipeline: Pipeline, stage: Stage) -> str:
    """Model registration only, deliberately not a duplicate of Layer 2's own
    gates: gate enforcement is engine-agnostic and runs as its own DAG task
    (docs/layer2.md, Concepts #4), not via `dbt test` - a dbt-engine stage's
    schema.yml exists so `dbt docs` has something to show, not to test.
    """
    data = {
        "version": 2,
        "models": [
            {"name": model,
             "description": f"{stage.name} stage of the {pipeline.name} pipeline "
                            f"(see pipelines/{pipeline.name}/pipeline.yaml)"}
            for model in stage.models
        ],
    }
    return yaml.safe_dump(data, sort_keys=False)


def artifact_paths(pipeline: Pipeline) -> dict[str, Path]:
    """Where write_artifacts() puts things - pipelines/<name>/build/, not a
    live Airflow DAGS_FOLDER or dbt project. Actually installing generated
    files where Airflow/dbt pick them up is a later step, tested against a
    real running Airflow rather than guessed at here.
    """
    build = pipeline.root / "build"
    paths = {"dag": build / "dags" / f"{pipeline.name}.py"}
    for stage in pipeline.stages[1:]:
        if stage.engine == "dbt":
            paths[f"schema_{stage.name}"] = (
                build / "models" / pipeline.name / stage.name / "schema.yml")
    return paths


def write_artifacts(pipeline: Pipeline) -> list[Path]:
    written = []
    paths = artifact_paths(pipeline)

    dag_path = paths["dag"]
    dag_path.parent.mkdir(parents=True, exist_ok=True)
    dag_path.write_text(render_dag(pipeline))
    written.append(dag_path)

    for stage in pipeline.stages[1:]:
        key = f"schema_{stage.name}"
        if key not in paths:
            continue
        schema_path = paths[key]
        schema_path.parent.mkdir(parents=True, exist_ok=True)
        schema_path.write_text(render_dbt_schema(pipeline, stage))
        written.append(schema_path)

    return written


def _psql_command(pipeline: Pipeline, *extra: str) -> tuple[list[str], dict[str, str]]:
    resolved = resolve_refs(
        {"host": pipeline.warehouse.host, "port": pipeline.warehouse.port,
         "database": pipeline.warehouse.database, "user": pipeline.warehouse.user,
         "password": pipeline.warehouse.password},
        path=f"{pipeline.name}.warehouse",
    )
    cmd = ["psql", "-h", resolved["host"], "-p", str(resolved["port"]),
           "-d", resolved["database"], "-v", "ON_ERROR_STOP=1"]
    if resolved.get("user"):
        cmd += ["-U", resolved["user"]]
    cmd += list(extra)
    env = os.environ.copy()
    if resolved.get("password"):
        env["PGPASSWORD"] = resolved["password"]
    # A procedure file's own SQL is unqualified ("TRUNCATE TABLE fct_sales",
    # not "demo.fct_sales") - same gap as runtime.py's _warehouse_conn, found
    # the same way: warehouse.schema was declared but never applied to the
    # session it runs the migration against.
    env["PGOPTIONS"] = f"-c search_path={pipeline.warehouse.schema},public"
    return cmd, env


def apply_procedures(pipeline: Pipeline) -> list[str]:
    """`CREATE OR REPLACE PROCEDURE` for every procedure-engine stage -
    idempotent by construction (docs/layer2.md, Concepts #3), so re-running
    deploy after an unrelated manifest edit re-applies every procedure
    harmlessly rather than needing to track which one actually changed.
    """
    applied = []
    for stage in pipeline.stages[1:]:
        if stage.engine != "procedure":
            continue
        cmd, env = _psql_command(pipeline, "-f", str(pipeline.path(stage.procedure)))
        proc = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=60)
        if proc.returncode != 0:
            raise DeployError(
                f"applying {stage.procedure} for stage {stage.name!r} failed:\n"
                f"{proc.stderr.strip()}")
        applied.append(stage.name)
    return applied


def deploy(pipeline: Pipeline, *, apply_db: bool = True) -> DeployResult:
    result = DeployResult()
    result.written = write_artifacts(pipeline)
    if apply_db:
        result.procedures_applied = apply_procedures(pipeline)
    return result


def _airflow_paths() -> tuple[Path, Path]:
    """(venv bin dir, env file) for the installed airflow pack - the same
    convention `packs/airflow/af-lib.sh`'s af_venv/af_env_file use, read from
    the pack's own recorded install params (falling back to the pack's
    default) rather than hard-coding `/opt/airflow`, since install_dir is a
    pack param a real install can override."""
    from ..engine import state
    from ..library import loader as packs_mod

    pack = packs_mod.load("airflow")
    install_dir = (pack.param_schema.get("install_dir") or {}).get("default", "/opt/airflow")
    record = state.get_install("airflow")
    if record:
        supplied = json.loads(record["params_json"])
        install_dir = supplied.get("install_dir", install_dir)
    install_dir = Path(install_dir)
    return install_dir / ".venv" / "bin", install_dir / "home" / "airflow.env"


def trigger_dag_command(pipeline_name: str, dpagent_run_id: int) -> list[str]:
    """The exact command `dpagent pipeline run` shells out to - built here,
    separately from the subprocess call, so it can be printed/tested without
    actually running it (mirrors `_psql_command`).

    Same shape as `af_run` in af-lib.sh: run as the `airflow` OS user with
    its env file sourced and its venv on PATH, since the airflow CLI must
    run as the user the webserver/scheduler/metadata DB were set up for."""
    venv_bin, env_file = _airflow_paths()
    conf = json.dumps({"dpagent_run_id": dpagent_run_id})
    inner = (
        f'set -a; source "{env_file}"; set +a; '
        f'export PATH="{venv_bin}:$PATH"; '
        f'exec "{venv_bin}/airflow" dags trigger "{pipeline_name}" --conf {conf!r}'
    )
    return ["sudo", "-u", "airflow", "bash", "-c", inner]


def trigger_dag(pipeline_name: str, dpagent_run_id: int) -> subprocess.CompletedProcess:
    cmd = trigger_dag_command(pipeline_name, dpagent_run_id)
    return subprocess.run(cmd, capture_output=True, text=True, timeout=60)
