"""Writes what `plan()` described to disk, and applies procedure migrations
for real.

dpagent has never linked a database driver into its own Python - every
pack's relationship with Postgres goes through `psql` as a subprocess
(`packs/postgres/pg-lib.sh`'s `pg_query`, e.g.), reviewed and auditable the
same way every other command this project runs is. This keeps that shape
rather than adding psycopg2 as a new dependency for one feature.
"""
from __future__ import annotations

import grp
import json
import os
import shutil
import stat
import subprocess
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from ..engine.params import resolve_refs
from .generator import dag_tasks
from .loader import Pipeline, Stage

# Same convention as library.loader's own _INSTALL_PREFIX (/opt/dpagent) -
# a location every local OS user can read, not a developer's own checkout.
# `install_pipeline_files()` publishes each deployed pipeline's manifest +
# procedures here so Airflow's own `airflow` user can read them too, the
# same reason dpagent's own code has to be pip-installed rather than just
# imported from wherever `dpagent pipeline deploy` happens to run.
SHARED_PIPELINES_DIR = Path("/opt/dpagent/pipelines")


class DeployError(Exception):
    pass


@dataclass
class DeployResult:
    written: list[Path] = field(default_factory=list)
    procedures_applied: list[str] = field(default_factory=list)
    dbt_models_published: list[Path] = field(default_factory=list)
    pipeline_files_published: Path | None = None
    airflow_bridge_actions: list[str] = field(default_factory=list)
    dag_installed: Path | None = None


def render_dag(pipeline: Pipeline) -> str:
    """A real, importable Airflow DAG - PythonOperator tasks calling into
    `dpagent.pipelines.runtime`, the gate/transform execution engine.

    Two preconditions this file relies on but cannot fully satisfy alone,
    both found by actually deploying to a real Airflow and watching it fail
    to import, not guessed at:

    1. dpagent must be pip-installed into Airflow's own venv (`<airflow
       install_dir>/.venv`), not merely importable from wherever `dpagent
       pipeline deploy` itself runs. A `sys.path.insert` pointing at
       dpagent's source directory was tried first and does not work: on a
       real host, dpagent's source lived under a developer's home
       directory (mode 700), which the `airflow` OS user has no traverse
       permission into at all, regardless of what sys.path says. A real
       `pip install` copies the package into a location the `airflow` user
       already owns and can read - also just the architecturally correct
       fix, since production Airflow should not depend on a specific
       developer's home directory being reachable.
    2. Once dpagent itself is reachable, `loader.load()` still needs this
       pipeline's own manifest/procedures - the exact same unreadable-home-
       directory problem one layer up. `os.environ.setdefault` below points
       `DPAGENT_PIPELINES` at `install_pipeline_files()`'s published copy
       (`SHARED_PIPELINES_DIR`) *before* importing `runtime` (which is what
       first imports `loader.py`, whose `PIPELINES_DIR` is computed once,
       at that import) - `setdefault` rather than a plain assignment so an
       operator's own explicit `DPAGENT_PIPELINES` (set some other way)
       still wins.
    """
    tasks = dag_tasks(pipeline)
    lines = [
        f'"""Generated by `dpagent pipeline deploy {pipeline.name}` - do not '
        f'hand-edit.',
        f"",
        f"Source of truth: pipelines/{pipeline.name}/pipeline.yaml. Change that,",
        f"then re-run deploy, instead of editing this file directly - it will",
        f"be overwritten the next time deploy runs. Requires dpagent to be",
        f'pip-installed into this Airflow install\'s own venv - see this',
        f'function\'s own docstring in deploy.py."""',
        "import os",
        "from datetime import datetime",
        "",
        f'os.environ.setdefault("DPAGENT_PIPELINES", {str(SHARED_PIPELINES_DIR)!r})',
        "",
        "from airflow import DAG",
        "from airflow.operators.python import PythonOperator",
        "",
        "from dpagent.pipelines import runtime",
        "",
        "",
        "with DAG(",
        f'    dag_id="{pipeline.name}",',
        "    schedule_interval=None,",
        "    start_date=datetime(2026, 1, 1),",
        "    catchup=False,",
        '    tags=["dpagent-pipeline"],',
        ") as dag:",
    ]

    for task in tasks:
        if task.kind == "extract":
            call = f'runtime.run_extract(pipeline_name="{pipeline.name}", run_id=run_id)'
        elif task.kind == "gate":
            stage_name = task.id[len("gate_"):]
            call = (f'runtime.run_gate(pipeline_name="{pipeline.name}", '
                    f'stage="{stage_name}", run_id=run_id)')
        else:
            stage_name = task.id[len("transform_"):]
            call = (f'runtime.run_transform(pipeline_name="{pipeline.name}", '
                    f'stage="{stage_name}", run_id=run_id)')
        # `run_id` is dpagent's own runs.id (kind='data'), started by `dpagent
        # pipeline run` before it triggers this DAG - passed through
        # dag_run.conf so every task's stage_runs/gate_runs/events row ties
        # back to that one run, the same run `dpagent audit <run>` reads.
        lines.append(f'    def _{task.id}(dag_run=None, **_):')
        lines.append(f'        run_id = (dag_run.conf or {{}}).get("dpagent_run_id") '
                     f'if dag_run else None')
        lines.append(f'        {call}')
        lines.append(f'')
        lines.append(f'    {task.id} = PythonOperator(')
        lines.append(f'        task_id="{task.id}",')
        lines.append(f'        python_callable=_{task.id},')
        lines.append(f'    )')

    for task in tasks:
        for dep in task.depends_on:
            lines.append(f"    {dep} >> {task.id}")

    return "\n".join(lines) + "\n"


def render_dbt_schema(pipeline: Pipeline, stage: Stage) -> str:
    """Model registration only, deliberately not a duplicate of Layer 2's own
    gates: gate enforcement is engine-agnostic and runs as its own DAG task
    (docs/layer2.md, Concepts #4), not via `dbt test` - a dbt-engine stage's
    schema.yml exists so `dbt docs` has something to show, not to test.
    """
    data = {
        "version": 2,
        "models": [
            {"name": model,
             "description": f"{stage.name} stage of the {pipeline.name} pipeline "
                            f"(see pipelines/{pipeline.name}/pipeline.yaml)"}
            for model in stage.models
        ],
    }
    return yaml.safe_dump(data, sort_keys=False)


def artifact_paths(pipeline: Pipeline) -> dict[str, Path]:
    """Where write_artifacts() puts things - pipelines/<name>/build/, a
    reviewable copy, not a live Airflow DAGS_FOLDER or dbt project.
    `install_dag()` is the separate step that actually copies the DAG to
    where Airflow's scheduler polls.
    """
    build = pipeline.root / "build"
    paths = {"dag": build / "dags" / f"{pipeline.name}.py"}
    for stage in pipeline.stages[1:]:
        if stage.engine == "dbt":
            paths[f"schema_{stage.name}"] = (
                build / "models" / pipeline.name / stage.name / "schema.yml")
    return paths


def write_artifacts(pipeline: Pipeline) -> list[Path]:
    written = []
    paths = artifact_paths(pipeline)

    dag_path = paths["dag"]
    dag_path.parent.mkdir(parents=True, exist_ok=True)
    dag_path.write_text(render_dag(pipeline))
    written.append(dag_path)

    for stage in pipeline.stages[1:]:
        key = f"schema_{stage.name}"
        if key not in paths:
            continue
        schema_path = paths[key]
        schema_path.parent.mkdir(parents=True, exist_ok=True)
        schema_path.write_text(render_dbt_schema(pipeline, stage))
        written.append(schema_path)

    return written


def _psql_command(pipeline: Pipeline, *extra: str) -> tuple[list[str], dict[str, str]]:
    resolved = resolve_refs(
        {"host": pipeline.warehouse.host, "port": pipeline.warehouse.port,
         "database": pipeline.warehouse.database, "user": pipeline.warehouse.user,
         "password": pipeline.warehouse.password},
        path=f"{pipeline.name}.warehouse",
    )
    cmd = ["psql", "-h", resolved["host"], "-p", str(resolved["port"]),
           "-d", resolved["database"], "-v", "ON_ERROR_STOP=1"]
    if resolved.get("user"):
        cmd += ["-U", resolved["user"]]
    cmd += list(extra)
    env = os.environ.copy()
    if resolved.get("password"):
        env["PGPASSWORD"] = resolved["password"]
    # A procedure file's own SQL is unqualified ("TRUNCATE TABLE fct_sales",
    # not "demo.fct_sales") - same gap as runtime.py's _warehouse_conn, found
    # the same way: warehouse.schema was declared but never applied to the
    # session it runs the migration against.
    env["PGOPTIONS"] = f"-c search_path={pipeline.warehouse.schema},public"
    return cmd, env


def apply_procedures(pipeline: Pipeline) -> list[str]:
    """`CREATE OR REPLACE PROCEDURE` for every procedure-engine stage -
    idempotent by construction (docs/layer2.md, Concepts #3), so re-running
    deploy after an unrelated manifest edit re-applies every procedure
    harmlessly rather than needing to track which one actually changed.
    """
    applied = []
    for stage in pipeline.stages[1:]:
        if stage.engine != "procedure":
            continue
        cmd, env = _psql_command(pipeline, "-f", str(pipeline.path(stage.procedure)))
        proc = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=60)
        if proc.returncode != 0:
            raise DeployError(
                f"applying {stage.procedure} for stage {stage.name!r} failed:\n"
                f"{proc.stderr.strip()}")
        applied.append(stage.name)
    return applied


def install_pipeline_files(pipeline: Pipeline) -> Path:
    """Publishes this pipeline's manifest + procedures to
    `SHARED_PIPELINES_DIR/<name>` - world-readable (root:root, 755/644), so
    the `airflow` OS user (or any other local user) can read them
    regardless of where the git checkout `dpagent pipeline deploy` itself
    ran from lives. Only this one pipeline's directory is copied, not the
    whole pipelines/ tree, so a deploy of one pipeline never exposes
    another that might still be mid-review. `build/` is excluded - it is
    itself derived from what gets published here, not an input to it.

    Requires root, same as `install_dag()`: /opt is not writable otherwise,
    and files must end up world-readable regardless of the deploying
    user's own umask.
    """
    if hasattr(os, "geteuid") and os.geteuid() != 0:
        raise DeployError(
            "publishing pipeline files to a host-wide-readable location "
            "needs root - re-run as sudo -E dpagent pipeline deploy ...")
    dest = SHARED_PIPELINES_DIR / pipeline.name
    if dest.exists():
        shutil.rmtree(dest)
    SHARED_PIPELINES_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copytree(pipeline.root, dest, ignore=shutil.ignore_patterns("build"))
    SHARED_PIPELINES_DIR.chmod(0o755)
    dest.chmod(0o755)
    for path in dest.rglob("*"):
        path.chmod(0o755 if path.is_dir() else 0o644)
    return dest


_DBT_SCHEMA_NAME_MACRO = """\
{% macro generate_schema_name(custom_schema_name, node) -%}
    {%- if custom_schema_name is none -%}
        {{ target.schema }}
    {%- else -%}
        {{ custom_schema_name | trim }}
    {%- endif -%}
{%- endmacro %}
"""


def _dbt_project_dir() -> Path:
    """The dbt pack's own project_dir - same lookup shape as
    _airflow_install_dir(). Safe to use packs_mod here (unlike
    runtime._dbt_project_dir's own, deliberately packs_mod-free twin):
    everything in this module runs on the CLI side, as whatever user calls
    `dpagent pipeline deploy`, never inside a DAG task's own process."""
    from ..engine import state
    from ..library import loader as packs_mod

    pack = packs_mod.load("dbt")
    project_dir = (pack.param_schema.get("project_dir") or {}).get("default", "/opt/dbt/project")
    record = state.get_install("dbt")
    if record:
        supplied = json.loads(record["params_json"])
        project_dir = supplied.get("project_dir", project_dir)
    return Path(project_dir)


def install_dbt_models(pipeline: Pipeline) -> list[Path]:
    """Publishes every dbt-engine stage's models/<name>.sql + a generated
    schema.yml into the dbt pack's own real project - `dbt run` only ever
    looks inside its own --project-dir, never at a pipeline's own
    directory (pipeline.root has no dbt_project.yml and never did;
    runtime.run_transform's dbt branch failed against it the first time it
    actually ran for real).

    Also ensures the project's generate_schema_name macro returns a
    model's own `schema` config verbatim: dbt's own default instead
    concatenates it with the target's default schema
    (`<target_schema>_<custom_schema>`), so a model declaring
    `schema: demo` would materialise into a schema dpagent's own gates
    (which read pipeline.yaml's warehouse.schema literally) would never
    find anything in. Written once, only if the project does not already
    have one - a real project might already carry its own override this
    must not silently replace.

    Lands under the dbt project's own dbtread-group default ACL
    (packs/dbt/steps/30-project.sh already applies one to the whole
    project directory), so no chmod/chgrp of its own is needed here -
    unlike install_pipeline_files()/install_dag(), which publish into
    locations with no such default in place.

    Requires root: /opt/dbt/project is not writable otherwise.
    """
    if hasattr(os, "geteuid") and os.geteuid() != 0:
        raise DeployError(
            "publishing dbt models needs root (writing into the dbt pack's "
            "own project directory) - re-run as sudo -E dpagent pipeline deploy ...")

    project_dir = _dbt_project_dir()
    macro_path = project_dir / "macros" / "generate_schema_name.sql"
    if not macro_path.exists():
        macro_path.parent.mkdir(parents=True, exist_ok=True)
        macro_path.write_text(_DBT_SCHEMA_NAME_MACRO)

    written = []
    dest_dir = project_dir / "models" / pipeline.name
    dest_dir.mkdir(parents=True, exist_ok=True)
    for stage in pipeline.stages[1:]:
        if stage.engine != "dbt":
            continue
        for model in stage.models:
            src = pipeline.root / "models" / f"{model}.sql"
            if not src.exists():
                raise DeployError(
                    f"stage {stage.name!r} declares dbt model {model!r}, but "
                    f"{src} does not exist")
            dest = dest_dir / f"{model}.sql"
            dest.write_text(src.read_text())
            written.append(dest)
        schema_dest = dest_dir / f"schema_{stage.name}.yml"
        schema_dest.write_text(render_dbt_schema(pipeline, stage))
        written.append(schema_dest)
    return written


def deploy(pipeline: Pipeline, *, apply_db: bool = True,
          install_dag_to_airflow: bool = True) -> DeployResult:
    result = DeployResult()
    result.written = write_artifacts(pipeline)
    if apply_db:
        result.procedures_applied = apply_procedures(pipeline)
        result.dbt_models_published = install_dbt_models(pipeline)
    if install_dag_to_airflow:
        result.pipeline_files_published = install_pipeline_files(pipeline)
        result.airflow_bridge_actions = ensure_airflow_can_run_pipelines()
        result.dag_installed = install_dag(pipeline)
    return result


def _airflow_install_dir() -> Path:
    """The airflow pack's own install_dir - read from its recorded install
    params (falling back to the pack's default) rather than hard-coding
    `/opt/airflow`, since install_dir is a pack param a real install can
    override."""
    from ..engine import state
    from ..library import loader as packs_mod

    pack = packs_mod.load("airflow")
    install_dir = (pack.param_schema.get("install_dir") or {}).get("default", "/opt/airflow")
    record = state.get_install("airflow")
    if record:
        supplied = json.loads(record["params_json"])
        install_dir = supplied.get("install_dir", install_dir)
    return Path(install_dir)


def _airflow_paths() -> tuple[Path, Path]:
    """(venv bin dir, env file) for the installed airflow pack - the same
    convention `packs/airflow/af-lib.sh`'s af_venv/af_env_file use."""
    install_dir = _airflow_install_dir()
    return install_dir / ".venv" / "bin", install_dir / "home" / "airflow.env"


_SHARED_GROUP = "dpagent"   # airflow joins this to write dpagent's own journal


def _dpagent_checkout_root() -> Path:
    """This checkout's own root - src/dpagent/pipelines/deploy.py -> src/dpagent
    -> src -> repo root. Where an editable install into Airflow's venv
    (ensure_airflow_can_run_pipelines) actually points."""
    return Path(__file__).resolve().parent.parent.parent.parent


def _run_root_command(cmd: list[str], *, what: str) -> None:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise DeployError(f"{what} failed:\n{proc.stderr.strip() or proc.stdout.strip()}")


def ensure_airflow_can_run_pipelines() -> list[str]:
    """Makes true, idempotently, the three host preconditions a real
    Airflow run needs that were done by hand at least once getting `dpagent
    pipeline run` to actually work end to end (docs/layer2.md): exactly the
    kind of thing that must not stay "a step someone remembers on the next
    host." Returns what it actually changed - an empty list means a
    previous deploy (or manual setup) already left the host correct, which
    is the common case, not an error.

    Requires root, same reason install_dag()/install_pipeline_files() do:
    every action here (chgrp, usermod, an ACL grant, a pip install into
    another venv) needs it.
    """
    if hasattr(os, "geteuid") and os.geteuid() != 0:
        raise DeployError(
            "preparing Airflow to run pipelines needs root (group/ACL/venv "
            "changes) - re-run as sudo -E dpagent pipeline deploy ...")

    from ..engine import state

    done: list[str] = []

    # 1. A shared group so the `airflow` OS user can write dpagent's own
    # SQLite journal (stage_runs/gate_runs/events) - it only ever needed
    # read access before a DAG task existed that must record its own
    # results. Same shape as packs/dbt's own dbtread group (which
    # packs/airflow/steps/10-user.sh already joins airflow to, for the
    # analogous dbt-project-sharing reason) - just for a group dpagent
    # itself owns, since dbtread is dbt's own concept, not dpagent's.
    if subprocess.run(["getent", "group", _SHARED_GROUP], capture_output=True).returncode != 0:
        _run_root_command(["groupadd", _SHARED_GROUP], what=f"creating group {_SHARED_GROUP!r}")
        done.append(f"created group {_SHARED_GROUP!r}")

    members = subprocess.run(["id", "-nG", "airflow"], capture_output=True, text=True).stdout.split()
    if _SHARED_GROUP not in members:
        _run_root_command(["usermod", "-aG", _SHARED_GROUP, "airflow"],
                          what=f"adding airflow to group {_SHARED_GROUP!r}")
        done.append(f"added the airflow OS user to group {_SHARED_GROUP!r} - "
                    f"restart airflow-scheduler/airflow-webserver for this to take effect")

    journal_dir = state.DB_PATH.parent
    journal_dir.mkdir(parents=True, exist_ok=True)
    dir_stat = journal_dir.stat()
    if (grp.getgrgid(dir_stat.st_gid).gr_name != _SHARED_GROUP
            or not (dir_stat.st_mode & stat.S_IRWXG)):
        _run_root_command(["chgrp", "-R", _SHARED_GROUP, str(journal_dir)],
                          what="chgrp-ing dpagent's own journal directory")
        _run_root_command(["chmod", "-R", "g+rwX", str(journal_dir)],
                          what="making dpagent's own journal directory group-writable")
        done.append(f"{journal_dir} is now group-writable by {_SHARED_GROUP!r}")

    # 2. A narrow ACL so the `airflow` OS user can traverse to wherever this
    # checkout actually lives - the first ancestor directory not already
    # traversable by anyone (a developer's own home directory at mode 700,
    # on the host this was first found on). Execute-only: `ls` there as
    # airflow still fails, only a known subpath works.
    checkout_root = _dpagent_checkout_root()
    for ancestor in [checkout_root, *checkout_root.parents]:
        if ancestor.stat().st_mode & stat.S_IXOTH:
            break   # already traversable by anyone from here up
        _run_root_command(["setfacl", "-m", "u:airflow:x", str(ancestor)],
                          what=f"granting airflow traverse access to {ancestor}")
        done.append(f"granted airflow traverse (execute-only) ACL on {ancestor}")

    # 3. dpagent importable from Airflow's own venv - editable, so a code
    # change takes effect immediately (a *regular* pip install does not -
    # it freezes a copy that silently goes stale, found the hard way).
    venv_bin, _ = _airflow_paths()
    already_importable = subprocess.run(
        [str(venv_bin / "python"), "-c", "import dpagent"], capture_output=True).returncode == 0
    if not already_importable:
        _run_root_command(
            [str(venv_bin / "pip"), "install", "-e", str(checkout_root), "--no-deps"],
            what="installing dpagent (editable) into Airflow's venv")
        done.append(f"installed dpagent (editable) into {venv_bin}")

    return done


def install_dag(pipeline: Pipeline) -> Path:
    """Copies the rendered DAG into Airflow's real DAGS_FOLDER
    (`<install_dir>/home/dags/<name>.py`, the same path `af_home()/dags`
    resolves to in af-lib.sh) and hands it to the `airflow` OS user -
    `af_home()`'s own directory is 700 airflow-only
    (packs/airflow/steps/10-user.sh), so the scheduler only ever sees a DAG
    file that actually belongs to it, the same way
    suites/airflow/setup/00-fixtures.sh writes its own throwaway DAGs.

    Requires root: chown-ing to a different user always does. write_artifacts()'s
    build/ copy needs no such privilege, which is why this is a separate,
    explicit step rather than folded into it.
    """
    if hasattr(os, "geteuid") and os.geteuid() != 0:
        raise DeployError(
            "installing the DAG into Airflow's real DAGS_FOLDER needs root "
            "(it must chown the file to the airflow user) - re-run as "
            "sudo -E dpagent pipeline deploy ...")
    dags_dir = _airflow_install_dir() / "home" / "dags"
    dags_dir.mkdir(parents=True, exist_ok=True)
    dag_path = dags_dir / f"{pipeline.name}.py"
    dag_path.write_text(render_dag(pipeline))
    dag_path.chmod(0o644)
    shutil.chown(dag_path, user="airflow", group="airflow")
    return dag_path


def trigger_dag_command(pipeline_name: str, dpagent_run_id: int) -> list[str]:
    """The exact command `dpagent pipeline run` shells out to - built here,
    separately from the subprocess call, so it can be printed/tested without
    actually running it (mirrors `_psql_command`).

    Same shape as `af_run` in af-lib.sh: run as the `airflow` OS user with
    its env file sourced and its venv on PATH, since the airflow CLI must
    run as the user the webserver/scheduler/metadata DB were set up for."""
    venv_bin, env_file = _airflow_paths()
    conf = json.dumps({"dpagent_run_id": dpagent_run_id})
    inner = (
        f'set -a; source "{env_file}"; set +a; '
        f'export PATH="{venv_bin}:$PATH"; '
        f'exec "{venv_bin}/airflow" dags trigger "{pipeline_name}" --conf {conf!r}'
    )
    return ["sudo", "-u", "airflow", "bash", "-c", inner]


def trigger_dag(pipeline_name: str, dpagent_run_id: int) -> subprocess.CompletedProcess:
    cmd = trigger_dag_command(pipeline_name, dpagent_run_id)
    return subprocess.run(cmd, capture_output=True, text=True, timeout=60)
