"""Compiles a pipeline's `source:` section into the standalone Python script
`runtime.run_extract` runs (through the dlt pack's own venv python, never
imported into dpagent's own process - the same discipline that keeps
psycopg2 out of dpagent's Python, extended to dlt's own DB drivers).

Pure compilation only, same split as generator.py/deploy.py: this module
never opens a connection or executes anything - it turns a `Pipeline` into
script text. `runtime.py` resolves `${ENV_VAR}` secrets and actually runs it.
"""
from __future__ import annotations

import textwrap

from .loader import Pipeline

CONNECTORS = {"odoo_postgres", "csv"}


def landing_dataset(pipeline: Pipeline) -> str:
    """dlt's own dataset_name for this pipeline's landing stage - fixed by
    convention (docs/layer2.md: "dlt writes each table as-received into
    demo_landing.<table>"), independent of warehouse.schema (which is what
    the *dbt/procedure*-produced raw/curated stages share - landing is dlt's
    own output, not a choice, same as it has no engine to choose)."""
    return f"{pipeline.name}_landing"


def render_extract_script(pipeline: Pipeline) -> str:
    connector = pipeline.source.connector
    if connector not in CONNECTORS:
        raise ValueError(
            f"no extract script for connector {connector!r}; expected one of "
            f"{sorted(CONNECTORS)}")

    dataset = landing_dataset(pipeline)
    header = (
        f'"""Generated by dpagent\'s runtime.run_extract - do not hand-edit.\n'
        f"Source: pipelines/{pipeline.name}/pipeline.yaml\"\"\"\n"
    )

    if connector == "csv":
        pattern = pipeline.source.files["path"]
        return header + textwrap.dedent(f'''\
            import csv
            import glob
            import os

            import dlt


            def _resource_for(path):
                name = os.path.splitext(os.path.basename(path))[0]

                @dlt.resource(name=name, write_disposition="replace")
                def read_rows():
                    with open(path, newline="") as f:
                        for row in csv.DictReader(f):
                            yield row

                return read_rows()


            paths = sorted(glob.glob({pattern!r}))
            if not paths:
                raise SystemExit("no files matched {pattern}")

            pipeline = dlt.pipeline(
                pipeline_name={pipeline.name + "_extract"!r},
                destination=dlt.destinations.postgres(credentials=os.environ["DEST_URL"]),
                dataset_name={dataset!r},
            )
            info = pipeline.run([_resource_for(p) for p in paths])
            print(info)
        ''')

    # odoo_postgres: a source schema is optional in the manifest (Odoo's own
    # tables live in "public"); any other sql_database-shaped source can
    # still declare one via source.connection.schema.
    source_schema = pipeline.source.connection.get("schema", "public")
    return header + textwrap.dedent(f'''\
        import os

        import dlt
        from dlt.sources.sql_database import sql_database

        source = sql_database(
            credentials=os.environ["SRC_URL"],
            schema={source_schema!r},
            table_names={list(pipeline.source.tables)!r},
        )
        pipeline = dlt.pipeline(
            pipeline_name={pipeline.name + "_extract"!r},
            destination=dlt.destinations.postgres(credentials=os.environ["DEST_URL"]),
            dataset_name={dataset!r},
        )
        info = pipeline.run(source)
        print(info)
    ''')
