"""Compiles a pipeline's `source:` section into the standalone Python script
`runtime.run_extract` runs (through the dlt pack's own venv python, never
imported into dpagent's own process - the same discipline that keeps
psycopg2 out of dpagent's Python, extended to dlt's own DB drivers).

Pure compilation only, same split as generator.py/deploy.py: this module
never opens a connection or executes anything - it turns a `Pipeline` into
script text. `runtime.py` resolves `${ENV_VAR}` secrets and actually runs it.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from .loader import Pipeline

CONNECTORS = {"odoo_postgres", "csv", "rest_api", "sql_server"}


def landing_dataset(pipeline: Pipeline) -> str:
    """dlt's own dataset_name for this pipeline's landing stage - fixed by
    convention (docs/layer2.md: "dlt writes each table as-received into
    demo_landing.<table>"), independent of warehouse.schema (which is what
    the *dbt/procedure*-produced raw/curated stages share - landing is dlt's
    own output, not a choice, same as it has no engine to choose)."""
    return f"{pipeline.name}_landing"


def render_extract_script(pipeline: Pipeline) -> str:
    connector = pipeline.source.connector
    if connector not in CONNECTORS:
        raise ValueError(
            f"no extract script for connector {connector!r}; expected one of "
            f"{sorted(CONNECTORS)}")

    dataset = landing_dataset(pipeline)
    header = (
        f'"""Generated by dpagent\'s runtime.run_extract - do not hand-edit.\n'
        f"Source: pipelines/{pipeline.name}/pipeline.yaml\"\"\"\n"
    )

    if connector == "csv":
        pattern = pipeline.source.files["path"]
        if not Path(pattern).is_absolute():
            pattern = str(pipeline.root / pattern)
        return header + textwrap.dedent(f'''\
            import csv
            import glob
            import os

            import dlt


            def _resource_for(path):
                name = os.path.splitext(os.path.basename(path))[0]

                @dlt.resource(name=name, write_disposition="replace")
                def read_rows():
                    with open(path, newline="") as f:
                        for row in csv.DictReader(f):
                            yield row

                return read_rows()


            paths = sorted(glob.glob({pattern!r}))
            if not paths:
                raise SystemExit("no files matched {pattern}")

            pipeline = dlt.pipeline(
                pipeline_name={pipeline.name + "_extract"!r},
                destination=dlt.destinations.postgres(credentials=os.environ["DEST_URL"]),
                dataset_name={dataset!r},
            )
            info = pipeline.run([_resource_for(p) for p in paths])
            print(info)
        ''')

    if connector == "rest_api":
        # dlt's own rest_api_source tries to auto-detect a paginator from the
        # first response's shape (Link header, a "next" field, ...) - real,
        # confirmed against a live public API: an API whose pagination it
        # cannot detect falls back to SinglePagePaginator, which silently
        # reads only the first page rather than erroring. A manifest can
        # name one of dlt's own paginator types explicitly
        # (connection.paginator: json_link / header_link / page_number /
        # offset / cursor, ...) to avoid relying on that guess for any real
        # API with more data than fits on one page.
        base_url = pipeline.source.connection["base_url"]
        auth_type = pipeline.source.connection.get("auth_type", "none")
        paginator = pipeline.source.connection.get("paginator")
        resources = list(pipeline.source.resources)
        auth_literal = (
            '{"type": "bearer", "token": os.environ["SRC_AUTH_TOKEN"]}'
            if auth_type == "bearer" else "None"
        )
        client_config = {"base_url": base_url}
        if paginator:
            client_config["paginator"] = paginator
        client_items = ", ".join(f"{k!r}: {v!r}" for k, v in client_config.items())
        return header + textwrap.dedent(f'''\
            import os

            import dlt
            from dlt.sources.rest_api import rest_api_source

            source = rest_api_source(
                {{
                    "client": {{{client_items}, "auth": {auth_literal}}},
                    "resources": {resources!r},
                }},
                name={pipeline.name + "_extract"!r},
            )
            pipeline = dlt.pipeline(
                pipeline_name={pipeline.name + "_extract"!r},
                destination=dlt.destinations.postgres(credentials=os.environ["DEST_URL"]),
                dataset_name={dataset!r},
            )
            info = pipeline.run(source)
            print(info)
        ''')

    # odoo_postgres/sql_server: both are dlt.sources.sql_database-shaped -
    # the connector-specific part (which SQLAlchemy dialect/driver SRC_URL
    # uses) lives entirely in runtime.py's _connection_url() call, not here.
    # A source schema is optional in the manifest: Odoo's own tables live in
    # "public" (Postgres's default); SQL Server's equivalent default is
    # "dbo", never "public" - any other sql_database-shaped source can still
    # declare one explicitly via source.connection.schema regardless.
    default_schema = "dbo" if connector == "sql_server" else "public"
    source_schema = pipeline.source.connection.get("schema", default_schema)
    return header + textwrap.dedent(f'''\
        import os

        import dlt
        from dlt.sources.sql_database import sql_database

        source = sql_database(
            credentials=os.environ["SRC_URL"],
            schema={source_schema!r},
            table_names={list(pipeline.source.tables)!r},
        )
        pipeline = dlt.pipeline(
            pipeline_name={pipeline.name + "_extract"!r},
            destination=dlt.destinations.postgres(credentials=os.environ["DEST_URL"]),
            dataset_name={dataset!r},
        )
        info = pipeline.run(source)
        print(info)
    ''')
